name: RoseLoot
main: dev.rosewood.roseloot.RoseLoot
version: '@version@'
api-version: '1.14'
description: Manipulate loot of mobs, blocks, fishing, and chests
author: Esophose
softdepend: [PlaceholderAPI]
commands:
  rl:
    description: The base RoseLoot command
    aliases: [loot]
