name: RoseLoot
version: '@version@'
authors: [Esophose]
website: https://www.spigotmc.org/resources/101979/
main: dev.rosewood.roseloot.RoseLoot
api-version: '1.13'
description: Manipulate loot of mobs, blocks, fishing, chests, piglin bartering, and advancements
softdepend:
  - PlaceholderAPI
  - HeadDatabase
  - Vault
  - Treasury
  - PlayerPoints
  - TokenManager
  - eco
  - EcoBosses
  - MythicLib
  - MMOItems
  - ItemBridge
  - ExecutableItems
  - SCore
  - ItemsAdder
  - ItemsXL
  - Oraxen
  - CustomItems
  - ItemEdit
  - UberItems
  - Slimefun
  - MythicMobs
  - RoseStacker
permissions:
  roseloot.basecommand:
    description: Allows using the RoseLoot commands
    default: true
  roseloot.help.wiki:
    description: Allows viewing the RoseLoot wiki link in the help menu
    default: op
  roseloot.reload:
    description: Allows running the reload command
    default: op
  roseloot.test:
    description: Allows running the test command
    default: op
  roseloot.generate:
    description: Allows running the generate command
    default: op
  roseloot.copy:
    description: Allows running the copy command
    default: op
