name: RoseLoot
main: dev.rosewood.roseloot.RoseLoot
version: '@version@'
api-version: '1.13'
description: Manipulate loot of mobs, blocks, fishing, chests, and piglin bartering
author: Esophose
softdepend: [PlaceholderAPI, HeadDatabase]
commands:
  rl:
    description: The base RoseLoot command
    aliases: [roseloot, loot]
permissions:
  roseloot.reload:
    description: Allows running the reload command
    default: op
